### PR TITLE
Trying to fix ROI restoring, finding it fixed, and documenting and cleaning up

### PR DESCRIPTION
**Pull request by vigji**
This is embarassing.
I thought I had to fix the ROI restoring, Vilim told me that. While trying, I tried to figure out things how they work etc.
It took me some time to realize that it was fixed already. By the way, not it works :)

Refreshing everything in the main gui refresh method is quite funny, I'll go check how we deal with that in Stytra.

In the meantime, I figured out some minor things. Now users can specify settings filenames, and path to the instructions is configurable.

### CODE REVIEW

**Comment by vigji** [comment]
Also, giving @diegoasua all the credit he deserves for leaving the lab with his git credentials stored :D

**Comment by diegoasua** [comment]
> Also, giving @diegoasua all the credit he deserves for leaving the lab with his git credentials stored :D

That is very stingy of me, I will disable the token now ;)

**Comment by vilim** [comment]
So the PR #72 is redundant? Please check it Luigi and close it is the case

**Comment by vigji** [comment]
I will check again both branches in the microscope but yes, loading parameters from this branch was actually restoring ROI correclty. I guess Diego knows more? How is it possible if that PR is still open?

**Comment by diegoasua** [comment]
ROI does restore as long as one *does not close* the software. However this was solved in PR #72, that part of the code has to come here. Then also there was a fix to the Mock Camera. Finally it was open because I was trying to implement ROI selection through a cleaner way that also blocks rotation of the ROI that Nicholas Sofroniew suggested me

**Comment by vigji** [comment]
Ok, I can try to merge that PR into this one then!

**Comment by vilim** [comment]
@diegoasua If I understood it correctly, Sofroniew's suggestion would not work that well for us, because the only way to change the aspect ratio in this case would be to resize the window, which would be both inconvenient and imprecise.

**Comment by diegoasua** [comment]
You understood correctly. The aspect ratio was the big problem I was not able to solve. So so far we are better off sticking to a shapes layer

**Comment by diegoasua** [comment]
I'll have a look now

**Comment by diegoasua** [comment]
The way the code is right now is quite different from the state in which that PR took over and therefore merging is impossible, will have to rewrite whatever I did...

**Comment by diegoasua** [comment]
Does it restore correctly after reboot? If you save the settings

**Comment by vigji** [comment]
Ok, then I'll try to fix it again here

**Pull request merged**
