### PR TITLE
Docs framework

### PR DESCRIPTION
**Pull request by vigji**
Added stuff that seems to work to generate docs from Markdown files. This is quite neat for stuff like including the readme and in general write md instead of the rst pain; MyST still uses a funny Sphynx-like syntax for "directives" (functions) like including stuff or making the toctree, but it overall makes sense!
In the documentation they still suggest to go through rst files for the autodoc generation, and they provide a wrapper to read incorporate those in MyST; are we fine with that?

### CODE REVIEW

**Comment by vilim** [comment]
Looks good to me! What are the steps to add travis/github actions build?

**Comment by vigji** [comment]
I will try to draft a version of the deployment in the next commit, ideally nothing more than what we usually do at least at first order

**Comment by diegoasua** [comment]
Looking good!

**Comment by vigji** [comment]
Ok, everything for writing new pages in markdown and generate autodocs from the numpy docstrings should be in place. I am testing now automatic deployment; I guess after testing it we want it from commits on master only? 

Test stuff locally is very straightforward: 
```
cd docs
sphinx-apidoc ../sashimi -o source/
make html
```

And then just checkout the index.html file in `/sashimi/docs/build/html/index.html`

**Comment by diegoasua** [comment]
Yeah only to commits to master

**Comment by vigji** [comment]
Perfect, this should be ready to merge! All the documentation is generated and deployed [here](https://portugueslab.github.io/sashimi/). Feel free to edit the main index page - maybe the README.md could be imported there and then it is ready to add contents to the toctree!
Should be ready for merging now, after these tests I set it to deploy only from master.

**Pull request merged**
